apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      imagePullSecrets:
        - name: gar-pull
      containers:
        - name: api-user
          image: europe-central2-docker.pkg.dev/int20h-2026/wjb/api-user:v0.1.0 # {"$imagepolicy": "wjb:user-backend"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8080"
            - name: ConnectionStrings__LocalhostConnection
              valueFrom:
                secretKeyRef:
                  name: wjb-api-secret
                  key: CONNECTION_STRING
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
