apiVersion: v1
kind: Secret
metadata:
  name: wjb-api-secret
type: Opaque
stringData:
  CONNECTION_STRING: "Host=wjb-postgres;Port=5432;Database=wjb;Username=wjb;Password=wjb"
  JWT_SECRET: "jwt-secret-admin-token-wellness-builder"
