apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wjb

resources:
  - namespace.yaml
  - postgresql
  - admin-frontend
  - admin-backend
  - user-frontend
  - user-backend
  - gateway
  - flux-image-automation
  - migration-job.yaml
