apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wjb-postgres
spec:
  serviceName: wjb-postgres
  replicas: 1
  selector:
    matchLabels:
      app: wjb-postgres
  template:
    metadata:
      labels:
        app: wjb-postgres
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:17-3.5
          ports:
            - containerPort: 5432
              name: pg
          envFrom:
            - secretRef:
                name: wjb-postgres-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["bash","-lc","pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["bash","-lc","pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wjb-postgres-data
