apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admin-backend-image.yaml
  - admin-frontend-image.yaml
  - user-backend-image.yaml
  - user-frontend-image.yaml
  - migration-image.yaml
